-- Data vault schema for security and compliance tracking.
-- Stores invocation metadata, prompt safety results, and PII sanitization history.

-- HUB: Core invocation entity based on unique invocation hash
CREATE TABLE IF NOT EXISTS HUB_SECURITY_INVOCATION (
    HK_INVOCATION_ID VARCHAR(64) PRIMARY KEY,
    INVOCATION_ID VARCHAR(128) NOT NULL,
    LOAD_TIMESTAMP TIMESTAMP NOT NULL,
    RECORD_SOURCE VARCHAR(50) NOT NULL
);

-- SAT: Input Guardrail & Threat Evaluation Details
CREATE TABLE IF NOT EXISTS SAT_INPUT_GUARDRAIL (
    HK_INVOCATION_ID VARCHAR(64) NOT NULL,
    LOAD_TIMESTAMP TIMESTAMP NOT NULL,
    IS_SAFE BOOLEAN NOT NULL,
    DETECTED_THREATS TEXT,
    RECORD_SOURCE VARCHAR(50) NOT NULL,
    FOREIGN KEY (HK_INVOCATION_ID) REFERENCES HUB_SECURITY_INVOCATION(HK_INVOCATION_ID)
);

-- SAT: PII Sanitization Context & Redaction Results
CREATE TABLE IF NOT EXISTS SAT_PII_SANITIZATION (
    HK_INVOCATION_ID VARCHAR(64) NOT NULL,
    LOAD_TIMESTAMP TIMESTAMP NOT NULL,
    ORIGINAL_PROMPT_HASH VARCHAR(64) NOT NULL,
    SANITIZED_PROMPT TEXT NOT NULL,
    RECORD_SOURCE VARCHAR(50) NOT NULL,
    FOREIGN KEY (HK_INVOCATION_ID) REFERENCES HUB_SECURITY_INVOCATION(HK_INVOCATION_ID)
);